spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashopapp
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true #systemOut?? ???
        format_sql: true
        default_batch_fetch_size: 100 # 페이징과 한계 돌파

  thymeleaf:
    prefix: classpath:/templates/

# ??? ??
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
